# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170626_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='playlist'),
        ),
    ]
