# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_playlist_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
