# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170627_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liking',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
