# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170627_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
