# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_playlist_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
