# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170703_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
