# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170704_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilesCodeguida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilesFacebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilesGitHub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilesLinkedIn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilesReplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
