# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170704_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilesCodeguida',
            new_name='pCodeguida',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilesFacebook',
            new_name='pFacebook',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilesGitHub',
            new_name='pGitHub',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilesLinkedIn',
            new_name='pLinkedIn',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilesReplace',
            new_name='pReplace',
        ),
    ]
