# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170704_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='technology',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
