# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170704_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='technology',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 5, 54, 15, 64662, tzinfo=utc), verbose_name='Остання активність'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pTwitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pCodeguida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codeguida'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pFacebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pGitHub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pLinkedIn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pReplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Replace.org.ua'),
        ),
    ]
