# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170705_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(default=time.time, verbose_name='Остання активність'),
        ),
    ]
