# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20170705_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pCodeguida',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pFacebook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pGitHub',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pLinkedIn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pReplace',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pTwitter',
        ),
    ]
