# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20170705_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pCodeguida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codeguida'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pFacebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pGitHub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pGitLab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitLab'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pLinkedIn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pReplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Replace.org.ua'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pTwitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter'),
        ),
    ]
