# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_playlist_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='author_user',
        ),
    ]
