# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_tag_numb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Коментар')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата коментування')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
