# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20170727_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default5.png', null=True, upload_to='user_avatar'),
        ),
    ]
