# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20170728_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default0.png', null=True, upload_to='user_avatar'),
        ),
    ]
